
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0' on 'Sat Oct 10 2020 13:33:52 GMT+0100 (British Summer Time)'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class ArticleListing extends ContentItem {
    public subpages!: Elements.LinkedItemsElement<ContentItem>;
    public title!: Elements.TextElement;
    public metadataPageTitle!: Elements.TextElement;
    public metadataOpenGraphImage!: Elements.AssetsElement;
    public banner!: Elements.AssetsElement;
    public metadataPageDescription!: Elements.TextElement;
    public metadataPageKeywords!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'metadata__page_title') {
                    return 'metadataPageTitle';
                }
                if (elementName === 'metadata__open_graph_image') {
                    return 'metadataOpenGraphImage';
                }
                if (elementName === 'metadata__page_description') {
                    return 'metadataPageDescription';
                }
                if (elementName === 'metadata__page_keywords') {
                    return 'metadataPageKeywords';
                }
                return elementName;
            })
        });
    }
}
