
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class CodeBlock extends ContentItem {
    public code!: Elements.TextElement;
    public language!: Elements.TextElement;
    public sourceUrl!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'source_url') {
                    return 'sourceUrl';
                }
                return elementName;
            })
        });
    }
}
