
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Page extends ContentItem {
    public title!: Elements.TextElement;
    public subpages!: Elements.LinkedItemsElement<ContentItem>;
    public url!: Elements.UrlSlugElement;
    public content!: Elements.LinkedItemsElement<ContentItem>;
    public showInNavigation!: Elements.MultipleChoiceElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'show_in_navigation') {
                    return 'showInNavigation';
                }
                return elementName;
            })
        });
    }
}
