import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Tweet extends ContentItem {
  public tweetUrl!: Elements.TextElement;
  constructor() {
    super({
      propertyResolver: (elementName: string) => {
        if (elementName === 'tweet_url') {
          return 'tweetUrl';
        }
        return elementName;
      },
    });
  }
}
