name: Build for PR

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      uses: Borales/actions-yarn@v2.1.0
      with:
        # Yarn command
        cmd: yarn

    - name: Build
      uses: Borales/actions-yarn@v2.1.0
      with:
        # Yarn command
        cmd: yarn build
